### ISSUE TITLE
Calling bottle :unneeded is deprecated

### ISSUE THREAD

**Issue by kkovaletp** [anchore/homebrew-grype#1] opened 2021-10-26 07:44 UTC
When I've used brew today, I've got next warning:
`Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the anchore/grype tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/anchore/homebrew-grype/grype.rb:9`

**Comment by luhring** [comment] 2021-10-26 11:43
Hi @kkovaletp, good catch! And by coincidence, we just opened a similar issue in the Grype repo: https://github.com/anchore/grype/issues/476

cc: @wagoodman

**Comment by spiffcs** [comment] 2021-11-04 13:51
We're still waiting for changes in goreleaser to land so that we can make sure this autogenerated file does not come back with the offending line on the next release. Thanks all for the fast fixes here

**Comment by kkovaletp** [comment] 2021-11-22 07:00
This issue was fixed some time ago, but returned back. Just letting you know...

**Comment by bobbydennett** [comment] 2021-12-15 15:55
Yes... it looks like it is back in the latest commit -- https://github.com/anchore/homebrew-grype/commit/311df288b2299d760c50819d1aba2a65e0a8938f

**Comment by spiffcs** [comment] 2022-01-04 15:02
Closing this as we know the underlying issue which is `goreleaser`. Thanks everyone for reporting and we will keep on top of this if there are regressions in our release process.

**Closed as completed by spiffcs** 2022-01-04 15:02 UTC
